version: "3.8"

services:
  centos72:
#    image: test/centos7
    build:
      context: ./centos
      dockerfile: Dockerfile
    container_name: centos7-container_name
    ports:
      - "4444:4444"
    volumes:
      - /Users/quarks:/usr/local/yangzl
    tty: true
#    depends_on:
#      - consul
#      - provider-grpc
#      - provider-jsonrpc
#    links:
#      - consul
#    command: sh -c "echo 'waiting for provider...'; sleep 10 && java -jar ./*.jar"
